// list of games
var game = [
  'https://duckhuntjs.com/',
  'https://www.schillmania.com/survivor/', 
  'https://ellisonleao.github.io/clumsy-bird/',  
  'https://krofdrakula.github.io/squirts/',
  'https://lab.hakim.se/coil/', 
  'https://www.graememcc.co.uk/micropolisJS/',
  'https://ancientbeast.com/',  
  'https://razh.github.io/game-off-2013/', 
  'https://candy-demo.enclavegames.com/', 
  'https://giacomotag.io/hb/', 
  'http://www.anagramica.com/', 
  'https://wwwtyro.github.io/Astray/',
  'https://kenrick95.github.io/c4/demo/',
  'https://cykod.github.io/AlienInvasion/',
  'http://www.dougmcinnes.com/html-5-asteroids',
  'https://rogers.enclavegames.com/',
  'https://gamegur-us.github.io/circushtml5/',
  'https://ondras.github.io/custom-tetris/',
  'https://mrrar.github.io/spashal/',
  'http://hexgl.bkcore.com/',
  'https://play2048.co/',
  'http://congusbongus.itch.io/drunken-viking',
  'https://demonixis.github.io/Maze3D/',
  'https://satanas.github.io/infectors/',
  'https://bni.github.io/orbium/',
  'http://antila.github.io/ludum-dare-28/',
  'http://abefehr.com/parity/',
  'https://shapex.org/',
  'https://noahmoroze.com/swap/',
  'https://lulea.github.io/game-off-2012/',
  'https://binb.co/',
  'https://the-house.arturkot.pl/',
  'https://tomwhall.github.io/descensus2/',
  'https://hypersomnia.io/',
  'https://basicallydan.github.io/skifree.js/',
  'https://couchfriends.com/games.html',
  'https://avabranch.zolmeister.com/',
  'https://thepond.zolmeister.com/',
  'https://rabiroshan.github.io/snake_game/',
  'https://shapex.org/',
  'https://code.jerev.be/ggo13-transcube/',
  'https://zop.zolmeister.com/',
  'https://hextris.io/',
  'https://pacman.platzh1rsch.ch/',
  'http://0hh1.com/',
  'https://codeincomplete.com/games/racer/',
  'https://js13kgames.com/games/q1k3',
  'https://js13kgames.com/games/tenacity',
  'https://chiaogu.github.io/stolen-sword/',
  'https://js13kgames.com/games/retrohaunt',
  'https://js13kgames.com/games/the-matr13k',
  'https://js13kgames.com/games/spacecraft',
  'https://js13kgames.com/games/re-wire',
  'https://gazijarin.github.io/AdamAI/'
]

// call the random game
function newGame() {
  var randomNumber = Math.floor(Math.random() * (game.length));
  // output
  document.getElementById('gameDisplay').innerHTML = game[randomNumber];
}
